---
title: "Project_Milestone_4"
author: "Cian Stryker"
date: "10/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(reshape2)
library(plyr)
library(janitor)
library(png)
library(gganimate)
library(tidyverse)
```

```{r}
Chinese_FDI <- read_excel("raw-data/China-Global-Investment-Tracker-2019-Spring-FINAL.xlsx", skip = 4) %>%
  clean_names()
```


```{r}
Freedom_scores <- read_excel("raw-data/Country and Territory Ratings and Statuses FIW1973-2018.xlsx")

```

```{r}
China_simple <- Chinese_FDI %>%
  select("year", "quantity_in_millions")

China_simple_1 <- aggregate(quantity_in_millions ~ year, data = China_simple, FUN = sum)

ggplot(China_simple_1, aes(x = year, y = quantity_in_millions, fill = year)) +
  guides(fill = FALSE) +
    geom_col()
```

```{r}
China <- Chinese_FDI %>%
  select("year", `quantity_in_millions`, "country", "region") 
  

China_1 <- aggregate(quantity_in_millions ~ country + year + region, data = China, FUN = sum)

China_1x <- China_1 %>%
  complete(year, nesting(country, region), fill = list(quantity_in_millions=0)) %>%
  arrange(year) %>%
  group_by(region, country) %>%
  mutate(y_cum = cumsum(quantity_in_millions))


ggplot(China_1x, aes(x = region, y = y_cum, fill = region)) +
  geom_col()+
  labs(x=NULL, y=NULL, fill=NULL, title="{closest_state}") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 16)) +
  transition_states(year, transition_length = 2, state_length = 1) +
  enter_fade() + 
  guides(fill = FALSE) +
  ease_aes('sine-in-out') 
  

```

```{r}
China2 <- Chinese_FDI %>% 
    select("year", `quantity_in_millions`, "country", "region") %>%
    filter(region %in% c("West Asia", 
                         "South America",
                         "Sub-Saharan Africa"
                          ))

China2_x <- aggregate(quantity_in_millions ~ country + year + region, data = China2, FUN = sum)


```

```{r}

trial <- China2_x %>%
  complete(year, nesting(country, region), fill = list(quantity_in_millions=0)) %>%
  arrange(year) %>%
  group_by(region, country) %>%
  mutate(y_cum = cumsum(quantity_in_millions))

ggplot(trial, aes(x = country, y = y_cum, size = y_cum, color = region)) +
  geom_point()+
  labs(x=NULL, y=NULL, fill=NULL, title="{closest_state}") +
  transition_states(year, transition_length = 2, state_length = 1) +
  enter_fade() + ease_aes('sine-in-out') + 
  theme_bw() +
  facet_wrap(~region)
```
